name: ic2s2tutorial
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - pandas
    - numpy<2.0.0
    - ujson
    - requests
    - jupyterlab
    - ipywidgets
    - protobuf==3.20.*
    - allennlp
    - matplotlib
    - torch
    - pyvis
    - igraph
    - networkx
    - scipy
    - scikit-learn
    - umap-learn
    - xnetwork
    - beautifulsoup4
    - sentence-transformers
    - emlens